package com.project.model;

public class NodeData extends NodeDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_data.nodeName
     *
     * @mbggenerated
     */
    private String nodename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_data.data
     *
     * @mbggenerated
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_data.allData
     *
     * @mbggenerated
     */
    private String alldata;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_data
     *
     * @mbggenerated
     */
    public NodeData(String timestamp, String deveui, String nodename, String data, String alldata) {
        super(timestamp, deveui);
        this.nodename = nodename;
        this.data = data;
        this.alldata = alldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_data
     *
     * @mbggenerated
     */
    public NodeData() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_data.nodeName
     *
     * @return the value of node_data.nodeName
     *
     * @mbggenerated
     */
    public String getNodename() {
        return nodename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_data.nodeName
     *
     * @param nodename the value for node_data.nodeName
     *
     * @mbggenerated
     */
    public void setNodename(String nodename) {
        this.nodename = nodename == null ? null : nodename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_data.data
     *
     * @return the value of node_data.data
     *
     * @mbggenerated
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_data.data
     *
     * @param data the value for node_data.data
     *
     * @mbggenerated
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_data.allData
     *
     * @return the value of node_data.allData
     *
     * @mbggenerated
     */
    public String getAlldata() {
        return alldata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_data.allData
     *
     * @param alldata the value for node_data.allData
     *
     * @mbggenerated
     */
    public void setAlldata(String alldata) {
        this.alldata = alldata == null ? null : alldata.trim();
    }
}