package com.project.model;

public class Nodeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.PI_MAC
     *
     * @mbggenerated
     */
    private String piMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.longitude
     *
     * @mbggenerated
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nodeinfo.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodeinfo
     *
     * @mbggenerated
     */
    public Nodeinfo(Integer id, String piMac, Integer state, String username, Double longitude, Double latitude, String ip) {
        this.id = id;
        this.piMac = piMac;
        this.state = state;
        this.username = username;
        this.longitude = longitude;
        this.latitude = latitude;
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nodeinfo
     *
     * @mbggenerated
     */
    public Nodeinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.id
     *
     * @return the value of nodeinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.id
     *
     * @param id the value for nodeinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.PI_MAC
     *
     * @return the value of nodeinfo.PI_MAC
     *
     * @mbggenerated
     */
    public String getPiMac() {
        return piMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.PI_MAC
     *
     * @param piMac the value for nodeinfo.PI_MAC
     *
     * @mbggenerated
     */
    public void setPiMac(String piMac) {
        this.piMac = piMac == null ? null : piMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.state
     *
     * @return the value of nodeinfo.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.state
     *
     * @param state the value for nodeinfo.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.username
     *
     * @return the value of nodeinfo.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.username
     *
     * @param username the value for nodeinfo.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.longitude
     *
     * @return the value of nodeinfo.longitude
     *
     * @mbggenerated
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.longitude
     *
     * @param longitude the value for nodeinfo.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.latitude
     *
     * @return the value of nodeinfo.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.latitude
     *
     * @param latitude the value for nodeinfo.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nodeinfo.ip
     *
     * @return the value of nodeinfo.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nodeinfo.ip
     *
     * @param ip the value for nodeinfo.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}