package com.project.model;

public class NodeDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_data.timestamp
     *
     * @mbggenerated
     */
    private String timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_data.devEUI
     *
     * @mbggenerated
     */
    private String deveui;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_data
     *
     * @mbggenerated
     */
    public NodeDataKey(String timestamp, String deveui) {
        this.timestamp = timestamp;
        this.deveui = deveui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_data
     *
     * @mbggenerated
     */
    public NodeDataKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_data.timestamp
     *
     * @return the value of node_data.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_data.timestamp
     *
     * @param timestamp the value for node_data.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp == null ? null : timestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_data.devEUI
     *
     * @return the value of node_data.devEUI
     *
     * @mbggenerated
     */
    public String getDeveui() {
        return deveui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_data.devEUI
     *
     * @param deveui the value for node_data.devEUI
     *
     * @mbggenerated
     */
    public void setDeveui(String deveui) {
        this.deveui = deveui == null ? null : deveui.trim();
    }
}