package com.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OutNodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public OutNodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDevEuiIsNull() {
            addCriterion("dev_eui is null");
            return (Criteria) this;
        }

        public Criteria andDevEuiIsNotNull() {
            addCriterion("dev_eui is not null");
            return (Criteria) this;
        }

        public Criteria andDevEuiEqualTo(String value) {
            addCriterion("dev_eui =", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiNotEqualTo(String value) {
            addCriterion("dev_eui <>", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiGreaterThan(String value) {
            addCriterion("dev_eui >", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiGreaterThanOrEqualTo(String value) {
            addCriterion("dev_eui >=", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiLessThan(String value) {
            addCriterion("dev_eui <", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiLessThanOrEqualTo(String value) {
            addCriterion("dev_eui <=", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiLike(String value) {
            addCriterion("dev_eui like", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiNotLike(String value) {
            addCriterion("dev_eui not like", value, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiIn(List<String> values) {
            addCriterion("dev_eui in", values, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiNotIn(List<String> values) {
            addCriterion("dev_eui not in", values, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiBetween(String value1, String value2) {
            addCriterion("dev_eui between", value1, value2, "devEui");
            return (Criteria) this;
        }

        public Criteria andDevEuiNotBetween(String value1, String value2) {
            addCriterion("dev_eui not between", value1, value2, "devEui");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorIsNull() {
            addCriterion("spreading_factor is null");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorIsNotNull() {
            addCriterion("spreading_factor is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorEqualTo(Integer value) {
            addCriterion("spreading_factor =", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorNotEqualTo(Integer value) {
            addCriterion("spreading_factor <>", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorGreaterThan(Integer value) {
            addCriterion("spreading_factor >", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorGreaterThanOrEqualTo(Integer value) {
            addCriterion("spreading_factor >=", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorLessThan(Integer value) {
            addCriterion("spreading_factor <", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorLessThanOrEqualTo(Integer value) {
            addCriterion("spreading_factor <=", value, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorIn(List<Integer> values) {
            addCriterion("spreading_factor in", values, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorNotIn(List<Integer> values) {
            addCriterion("spreading_factor not in", values, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorBetween(Integer value1, Integer value2) {
            addCriterion("spreading_factor between", value1, value2, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andSpreadingFactorNotBetween(Integer value1, Integer value2) {
            addCriterion("spreading_factor not between", value1, value2, "spreadingFactor");
            return (Criteria) this;
        }

        public Criteria andChannelGroupIsNull() {
            addCriterion("channel_group is null");
            return (Criteria) this;
        }

        public Criteria andChannelGroupIsNotNull() {
            addCriterion("channel_group is not null");
            return (Criteria) this;
        }

        public Criteria andChannelGroupEqualTo(Integer value) {
            addCriterion("channel_group =", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupNotEqualTo(Integer value) {
            addCriterion("channel_group <>", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupGreaterThan(Integer value) {
            addCriterion("channel_group >", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupGreaterThanOrEqualTo(Integer value) {
            addCriterion("channel_group >=", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupLessThan(Integer value) {
            addCriterion("channel_group <", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupLessThanOrEqualTo(Integer value) {
            addCriterion("channel_group <=", value, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupIn(List<Integer> values) {
            addCriterion("channel_group in", values, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupNotIn(List<Integer> values) {
            addCriterion("channel_group not in", values, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupBetween(Integer value1, Integer value2) {
            addCriterion("channel_group between", value1, value2, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andChannelGroupNotBetween(Integer value1, Integer value2) {
            addCriterion("channel_group not between", value1, value2, "channelGroup");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeIsNull() {
            addCriterion("last_packet_time is null");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeIsNotNull() {
            addCriterion("last_packet_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeEqualTo(Date value) {
            addCriterion("last_packet_time =", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeNotEqualTo(Date value) {
            addCriterion("last_packet_time <>", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeGreaterThan(Date value) {
            addCriterion("last_packet_time >", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_packet_time >=", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeLessThan(Date value) {
            addCriterion("last_packet_time <", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_packet_time <=", value, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeIn(List<Date> values) {
            addCriterion("last_packet_time in", values, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeNotIn(List<Date> values) {
            addCriterion("last_packet_time not in", values, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeBetween(Date value1, Date value2) {
            addCriterion("last_packet_time between", value1, value2, "lastPacketTime");
            return (Criteria) this;
        }

        public Criteria andLastPacketTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_packet_time not between", value1, value2, "lastPacketTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lora_web_node
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lora_web_node
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}