package com.project.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwdHash
     *
     * @mbggenerated
     */
    private String pwdhash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwdSalt
     *
     * @mbggenerated
     */
    private String pwdsalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User(String username, String pwdhash, String pwdsalt, Integer status) {
        this.username = username;
        this.pwdhash = pwdhash;
        this.pwdsalt = pwdsalt;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwdHash
     *
     * @return the value of user.pwdHash
     *
     * @mbggenerated
     */
    public String getPwdhash() {
        return pwdhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwdHash
     *
     * @param pwdhash the value for user.pwdHash
     *
     * @mbggenerated
     */
    public void setPwdhash(String pwdhash) {
        this.pwdhash = pwdhash == null ? null : pwdhash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwdSalt
     *
     * @return the value of user.pwdSalt
     *
     * @mbggenerated
     */
    public String getPwdsalt() {
        return pwdsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwdSalt
     *
     * @param pwdsalt the value for user.pwdSalt
     *
     * @mbggenerated
     */
    public void setPwdsalt(String pwdsalt) {
        this.pwdsalt = pwdsalt == null ? null : pwdsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}