package com.project.mapper;

import com.project.model.Gatewayinfo;
import com.project.model.GatewayinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface GatewayinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int countByExample(GatewayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int deleteByExample(GatewayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from gatewayinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into gatewayinfo (id, PI_MAC, ",
        "status, username, ",
        "longitude, latitude, ",
        "ip, frequency)",
        "values (#{id,jdbcType=INTEGER}, #{piMac,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{longitude,jdbcType=DOUBLE}, #{latitude,jdbcType=DOUBLE}, ",
        "#{ip,jdbcType=VARCHAR}, #{frequency,jdbcType=INTEGER})"
    })
    int insert(Gatewayinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int insertSelective(Gatewayinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    List<Gatewayinfo> selectByExample(GatewayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, PI_MAC, status, username, longitude, latitude, ip, frequency",
        "from gatewayinfo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Gatewayinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Gatewayinfo record, @Param("example") GatewayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Gatewayinfo record, @Param("example") GatewayinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Gatewayinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gatewayinfo
     *
     * @mbggenerated
     */
    @Update({
        "update gatewayinfo",
        "set PI_MAC = #{piMac,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER},",
          "username = #{username,jdbcType=VARCHAR},",
          "longitude = #{longitude,jdbcType=DOUBLE},",
          "latitude = #{latitude,jdbcType=DOUBLE},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "frequency = #{frequency,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Gatewayinfo record);
}