package com.project.mapper;

import com.project.model.Timeorder;
import com.project.model.TimeorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TimeorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int countByExample(TimeorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int deleteByExample(TimeorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    @Delete({
        "delete from timeorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    @Insert({
        "insert into timeorder (id, username, ",
        "starttime, endtime, ",
        "status)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{starttime,jdbcType=TIMESTAMP}, #{endtime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=INTEGER})"
    })
    int insert(Timeorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int insertSelective(Timeorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    List<Timeorder> selectByExample(TimeorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, username, starttime, endtime, status",
        "from timeorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Timeorder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Timeorder record, @Param("example") TimeorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Timeorder record, @Param("example") TimeorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Timeorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timeorder
     *
     * @mbggenerated
     */
    @Update({
        "update timeorder",
        "set username = #{username,jdbcType=VARCHAR},",
          "starttime = #{starttime,jdbcType=TIMESTAMP},",
          "endtime = #{endtime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Timeorder record);
}